version: '3.8'

services:
  ysweb:
    image: ${FRONTEND_IMAGE:-jimi-registry.cn-shanghai.cr.aliyuncs.com/jimi/ysweb:latest}
    container_name: ysweb
    restart: unless-stopped
    ports:
      - "${VITE_PORT:-80}:80"
    networks:
      - ysgo_network

networks:
  ysgo_network:
    external: true
